version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /backend/worker-prototype
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
