-- Catálogo inicial do Receitando

INSERT OR IGNORE INTO ingredients (id, name, normalized_name, category) VALUES ('ing-ovo', 'Ovo', 'ovo', 'proteínas');
INSERT OR IGNORE INTO ingredients (id, name, normalized_name, category) VALUES ('ing-banana', 'Banana', 'banana', 'frutas');
INSERT OR IGNORE INTO ingredients (id, name, normalized_name, category) VALUES ('ing-farinha-trigo', 'Farinha de trigo', 'farinha de trigo', 'grãos e farinhas');
INSERT OR IGNORE INTO ingredients (id, name, normalized_name, category) VALUES ('ing-leite', 'Leite', 'leite', 'laticínios');
INSERT OR IGNORE INTO ingredients (id, name, normalized_name, category) VALUES ('ing-fermento', 'Fermento', 'fermento', 'mercearia');
INSERT OR IGNORE INTO ingredients (id, name, normalized_name, category) VALUES ('ing-tomate', 'Tomate', 'tomate', 'vegetais');
INSERT OR IGNORE INTO ingredients (id, name, normalized_name, category) VALUES ('ing-cebola', 'Cebola', 'cebola', 'vegetais');
INSERT OR IGNORE INTO ingredients (id, name, normalized_name, category) VALUES ('ing-alho', 'Alho', 'alho', 'vegetais');
INSERT OR IGNORE INTO ingredients (id, name, normalized_name, category) VALUES ('ing-arroz', 'Arroz', 'arroz', 'grãos e farinhas');
INSERT OR IGNORE INTO ingredients (id, name, normalized_name, category) VALUES ('ing-macarrao', 'Macarrão', 'macarrao', 'massas');
INSERT OR IGNORE INTO ingredients (id, name, normalized_name, category) VALUES ('ing-queijo', 'Queijo', 'queijo', 'laticínios');
INSERT OR IGNORE INTO ingredients (id, name, normalized_name, category) VALUES ('ing-manteiga', 'Manteiga', 'manteiga', 'laticínios');
INSERT OR IGNORE INTO ingredients (id, name, normalized_name, category) VALUES ('ing-acucar', 'Açúcar', 'acucar', 'mercearia');
INSERT OR IGNORE INTO ingredients (id, name, normalized_name, category) VALUES ('ing-batata', 'Batata', 'batata', 'vegetais');
INSERT OR IGNORE INTO ingredients (id, name, normalized_name, category) VALUES ('ing-cenoura', 'Cenoura', 'cenoura', 'vegetais');
INSERT OR IGNORE INTO ingredients (id, name, normalized_name, category) VALUES ('ing-oleo', 'Óleo', 'oleo', 'óleos e gorduras');
INSERT OR IGNORE INTO ingredients (id, name, normalized_name, category) VALUES ('ing-sal', 'Sal', 'sal', 'temperos');

INSERT OR IGNORE INTO recipes (id, title, slug, description, instructions, prep_minutes, servings) VALUES ('rec-panqueca-banana', 'Panqueca de banana', 'panqueca-de-banana', 'Panquecas macias e naturalmente doces para um café da manhã rápido.', '1. Amasse a banana.\n2. Misture o ovo, o leite e a farinha até obter uma massa homogênea.\n3. Doure pequenas porções em uma frigideira aquecida.', 15, 2);
INSERT OR IGNORE INTO recipes (id, title, slug, description, instructions, prep_minutes, servings) VALUES ('rec-bolo-banana', 'Bolo de banana', 'bolo-de-banana', 'Bolo caseiro úmido, perfumado e fácil de preparar.', '1. Amasse as bananas e misture com os ovos e o leite.\n2. Incorpore a farinha e o açúcar.\n3. Adicione o fermento por último.\n4. Asse a 180 °C por cerca de 35 minutos.', 50, 8);
INSERT OR IGNORE INTO recipes (id, title, slug, description, instructions, prep_minutes, servings) VALUES ('rec-omelete-tomate', 'Omelete de tomate', 'omelete-de-tomate', 'Omelete leve com tomate, pronta em poucos minutos.', '1. Bata os ovos.\n2. Junte o tomate e a cebola picados.\n3. Tempere e cozinhe em frigideira tampada até firmar.', 12, 1);
INSERT OR IGNORE INTO recipes (id, title, slug, description, instructions, prep_minutes, servings) VALUES ('rec-arroz-legumes', 'Arroz com legumes', 'arroz-com-legumes', 'Arroz colorido e prático para acompanhar as refeições do dia a dia.', '1. Refogue o alho e a cebola.\n2. Acrescente arroz e cenoura.\n3. Cubra com água e cozinhe em fogo baixo até secar.', 30, 4);
INSERT OR IGNORE INTO recipes (id, title, slug, description, instructions, prep_minutes, servings) VALUES ('rec-macarrao-alho-oleo', 'Macarrão alho e óleo', 'macarrao-alho-e-oleo', 'Um clássico rápido, aromático e feito com poucos ingredientes.', '1. Cozinhe o macarrão até ficar al dente.\n2. Doure o alho no óleo em fogo baixo.\n3. Misture a massa escorrida e ajuste o sal.', 20, 2);
INSERT OR IGNORE INTO recipes (id, title, slug, description, instructions, prep_minutes, servings) VALUES ('rec-pure-batata', 'Purê de batata', 'pure-de-batata', 'Purê cremoso que combina com diferentes pratos.', '1. Cozinhe as batatas até ficarem macias.\n2. Amasse bem.\n3. Leve ao fogo baixo com leite e manteiga, mexendo até ficar cremoso.', 35, 4);
INSERT OR IGNORE INTO recipes (id, title, slug, description, instructions, prep_minutes, servings) VALUES ('rec-panqueca-simples', 'Panqueca simples', 'panqueca-simples', 'Massa básica de panqueca para receber recheios doces ou salgados.', '1. Bata o ovo, o leite e a farinha.\n2. Despeje uma camada fina em frigideira aquecida.\n3. Vire quando as bordas soltarem e doure o outro lado.', 20, 4);
INSERT OR IGNORE INTO recipes (id, title, slug, description, instructions, prep_minutes, servings) VALUES ('rec-omelete-queijo', 'Omelete de queijo', 'omelete-de-queijo', 'Omelete dourada com queijo derretido no centro.', '1. Bata os ovos.\n2. Despeje em uma frigideira aquecida.\n3. Adicione o queijo, dobre a omelete e cozinhe até derreter.', 10, 1);

INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-001', 'rec-panqueca-banana', 'ing-banana', 1, 'unidade', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-002', 'rec-panqueca-banana', 'ing-ovo', 1, 'unidade', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-003', 'rec-panqueca-banana', 'ing-farinha-trigo', 4, 'colheres de sopa', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-004', 'rec-panqueca-banana', 'ing-leite', 100, 'ml', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-005', 'rec-panqueca-banana', 'ing-manteiga', 1, 'colher de chá', 1);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-006', 'rec-bolo-banana', 'ing-banana', 3, 'unidades', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-007', 'rec-bolo-banana', 'ing-farinha-trigo', 2, 'xícaras', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-008', 'rec-bolo-banana', 'ing-ovo', 2, 'unidades', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-009', 'rec-bolo-banana', 'ing-leite', 1, 'xícara', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-010', 'rec-bolo-banana', 'ing-fermento', 1, 'colher de sopa', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-011', 'rec-bolo-banana', 'ing-acucar', 0.75, 'xícara', 1);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-012', 'rec-omelete-tomate', 'ing-ovo', 2, 'unidades', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-013', 'rec-omelete-tomate', 'ing-tomate', 1, 'unidade', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-014', 'rec-omelete-tomate', 'ing-cebola', 0.25, 'unidade', 1);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-015', 'rec-omelete-tomate', 'ing-sal', 1, 'pitada', 1);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-016', 'rec-arroz-legumes', 'ing-arroz', 1, 'xícara', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-017', 'rec-arroz-legumes', 'ing-cenoura', 1, 'unidade', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-018', 'rec-arroz-legumes', 'ing-cebola', 0.5, 'unidade', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-019', 'rec-arroz-legumes', 'ing-alho', 1, 'dente', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-020', 'rec-arroz-legumes', 'ing-sal', 1, 'pitada', 1);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-021', 'rec-macarrao-alho-oleo', 'ing-macarrao', 200, 'g', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-022', 'rec-macarrao-alho-oleo', 'ing-alho', 3, 'dentes', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-023', 'rec-macarrao-alho-oleo', 'ing-oleo', 3, 'colheres de sopa', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-024', 'rec-macarrao-alho-oleo', 'ing-sal', 1, 'pitada', 1);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-025', 'rec-pure-batata', 'ing-batata', 5, 'unidades', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-026', 'rec-pure-batata', 'ing-leite', 150, 'ml', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-027', 'rec-pure-batata', 'ing-manteiga', 2, 'colheres de sopa', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-028', 'rec-pure-batata', 'ing-sal', 1, 'pitada', 1);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-029', 'rec-panqueca-simples', 'ing-ovo', 1, 'unidade', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-030', 'rec-panqueca-simples', 'ing-farinha-trigo', 1, 'xícara', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-031', 'rec-panqueca-simples', 'ing-leite', 1, 'xícara', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-032', 'rec-panqueca-simples', 'ing-manteiga', 1, 'colher de chá', 1);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-033', 'rec-omelete-queijo', 'ing-ovo', 2, 'unidades', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-034', 'rec-omelete-queijo', 'ing-queijo', 50, 'g', 0);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-035', 'rec-omelete-queijo', 'ing-leite', 1, 'colher de sopa', 1);
INSERT OR IGNORE INTO recipe_ingredients (id, recipe_id, ingredient_id, quantity, unit, optional) VALUES ('ri-036', 'rec-omelete-queijo', 'ing-sal', 1, 'pitada', 1);
