/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f52259f94787cb6586948b0a36ac234f)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	FRONTEND_URL: "http://localhost:3000";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FRONTEND_URL">> {}
}
